baseURL = "https://luunguyen.netlify.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"
title = "Luu Nguyen's Blog"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-60116345-1"
disqusShortname = "nnluukhtn"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "A daddy, software engineer, currently Engineering Lead at [Hubble](https://hubble.sg/), focused on building and running Vietnam engineering team."
  homeMetaContent = "a daddy, software engineer, currently Engineering Lead at [Hubble](https://hubble.sg/), focused on building and running Vietnam engineering team."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "nnluukhtn"
  images = ["about/about_me.jpg"]

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
