baseURL = "https://luunguyen.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"
title = "Luu Nguyen's Blog"
theme = "hugo-theme-cactus"
googleAnalytics = "UA-60116345-1"
googleAnalyticsAsync = true
copyright = "Luu Nguyen"
disqusShortname = "nnluukhtn"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2


[params]
  colortheme = "white" # dark, light, white, or classic
  description = "A daddy, software engineer, currently Engineering Lead at hubble.sg, focus on building and running Vietnam engineering team."
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "January 2, 2006"
  images = ["about/about_me.jpg"]
  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = true
  rss = true
  showProjectsList = false
  css = ["css/custom.css"]
  js = ["js/custom.js"]
  logo = "images/logo.svg"

  [params.comments]
    enabled = true
    engine = "disqus"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/nnluukhtn/"

[[params.social]]
  name = "github"
  link = "https://github.com/nnluukhtn"

[[params.social]]
  name = "email"
  link = "nnluukhtn@gmail.com" # no need for "mailto:" at the start
